---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver
    apt: 
      name: "{{myubuntuserver}}"
      state: present
    when: ansible_os_family=="Debian" 

  - name: install webserver
    yum: 
      name: "{{myredhatserver}}"
      state: present
    when: ansible_os_family=="RedHat"
