---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver
    apt: 
      name: apache2
      state: present
      
  - name: start webservice
    service: 
      name: httpd
      state: started
